
INSERT INTO USER_MASTER(USER_NAME,USER_PASSWORD,PASSWORD_EXPIRY_DATE) VALUES ('rmw_admin','YWRtaW4=','2018-03-04');

INSERT INTO USER_MASTER(USER_NAME,USER_PASSWORD,PASSWORD_EXPIRY_DATE) VALUES ('piyush','cGl5dXNoMTIz','2020-12-29');

INSERT INTO USER_MASTER(USER_NAME,USER_PASSWORD,PASSWORD_EXPIRY_DATE) VALUES ('prtk','cHJ0azc4OQ==','2018-11-16');
